- hosts: localhost:freeradius
  become: false
  tasks:
    - name: Gather facts
      setup:
        gather_subset:
          - network

- hosts: all
  roles:
    - certificates

- hosts: node
  tasks:
    - name: Gather facts
      setup:
        gather_subset:
          - network
  roles:
    - strongswan

- hosts: database
  roles:
    - postgres
    - radius_db
    - main_db

- hosts: freeradius
  roles:
    - freeradius

- hosts: client
  roles:
    - strongswan_client
