---
- name: Set secret path
  set_fact:
    secret_dir: "{{ playbook_dir }}/inventory/host_vars/{{ inventory_hostname }}"
    secret_file: radius_secret.vault.yml

- name: Create secret directory
  delegate_to: localhost
  file:
    path: "{{ secret_dir }}"
    state: directory
    mode: "0755"
    owner: 1000

- name: Generate radius secret
  delegate_to: localhost
  when: radius_secret is not defined
  changed_when: true
  command: openssl rand -base64 32
  register: secret

- name: Set radius secret
  when: secret.changed
  set_fact:
    radius_secret: "{{ secret.stdout }}"

- name: Save strongswan secret
  delegate_to: localhost
  when: secret.changed
  copy:
    content: |
      radius_secret: "{{ radius_secret }}"
    dest: "{{ secret_dir }}/{{ secret_file }}"
    mode: "0600"
    owner: 1000
