---
- name: Set variables
  set_fact:
    nodes: "{{ groups['node'] | map('extract', hostvars) | list }}"
    conf_root: "/etc/raddb"

- name: Install freeradius
  apk:
    name:
      - freeradius
      - freeradius-eap
      - freeradius-sql
      - freeradius-postgresql
    state: present

- name: Include nftables
  include_role:
    name: nftables

- name: Copy server cert
  copy:
    remote_src: true
    src: "{{ cert_dir }}/{{ inventory_hostname }}.crt"
    dest: "{{ conf_root }}/certs/server.crt"
    owner: "radius"
    mode: "0640"
  notify: Restart freeradius

- name: Copy server key
  copy:
    remote_src: true
    src: "{{ cert_dir }}/host.key"
    dest: "{{ conf_root }}/certs/server.key"
    owner: "radius"
    mode: "0600"
  notify: Restart freeradius

- name: Copy EAP config
  template:
    src: eap.j2
    dest: "{{ conf_root }}/mods-enabled/eap"
    mode: "0640"
  notify: Restart freeradius

- name: Copy sql config
  template:
    src: sql.j2
    dest: "{{ conf_root }}/mods-enabled/sql"
    mode: "0640"
  notify: Restart freeradius

- name: Enable sql in radiusd.conf
  lineinfile:
    path: "{{ conf_root }}/radiusd.conf"
    insertafter: "^\\s*instantiate\\s*{"
    line: "\tsql"
  notify: Restart freeradius

- name: Install clients
  include_tasks: clients.yml
