---
- name: Set variables
  set_fact:
    nodes: "{{ groups['node'] | map('extract', hostvars) | list }}"
    conf_root: "/etc/raddb"

- name: Install freeradius
  apk:
    name:
      - freeradius
      - freeradius-eap
    state: present

- name: Include nftables
  include_role:
    name: nftables

- name: Copy clients.conf
  template:
    src: clients.conf.j2
    dest: "{{ conf_root }}/clients.conf"
    mode: "0640"
  notify: Restart freeradius

- name: Create clients.d
  file:
    path: "{{ conf_root }}/clients.d"
    state: directory
    mode: "0750"

- name: List contents of clients.d
  command: ls -1 "{{ conf_root }}/clients.d"
  changed_when: false
  register: contents

- name: Clean clients.d
  loop: "{{ contents.stdout_lines }}"
  when: item not in groups['node']
  file:
    path: "{{ conf_root }}/clients.d/{{ item }}.conf"
    state: absent

- name: Deploy clients
  vars:
    client: "{{ item.inventory_hostname }}"
    ipaddr: "{{ item.ansible_default_ipv4.address }}"
    secret: "{{ hostvars[item.inventory_hostname].radius_secret }}"
  loop: "{{ nodes }}"
  loop_control:
    label: "{{ item.inventory_hostname }}"
  template:
    src: client.conf.j2
    dest: "{{ conf_root }}/clients.d/{{ item.inventory_hostname }}.conf"
    mode: "0640"
  notify: Restart freeradius

- name: Deploy users
  vars:
    clients: "{{ groups['client'] | map('extract', hostvars) | list }}"
  template:
    src: users.j2
    dest: "{{ conf_root }}/mods-config/files/authorize"
    mode: "0640"

- name: Copy EAP config
  template:
    src: eap.j2
    dest: "{{ conf_root }}/mods-enabled/eap"
    mode: "0640"
  notify: Restart freeradius

- name: Copy server cert
  copy:
    remote_src: true
    src: "{{ cert_dir }}/{{ inventory_hostname }}.crt"
    dest: "{{ conf_root }}/certs/server.crt"
    owner: "radius"
    mode: "0640"
  notify: Restart freeradius

- name: Copy server key
  copy:
    remote_src: true
    src: "{{ cert_dir }}/host.key"
    dest: "{{ conf_root }}/certs/server.key"
    owner: "radius"
    mode: "0640"
  notify: Restart freeradius
